# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mainadress', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('contacts', models.IntegerField()),
                ('branches', models.CharField(max_length=100)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
